scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['ip-172-31-22-51.ec2.internal:9090']
        labels:
          application: 'monitoring'